### ISSUE TITLE
how can I find the optical filter band of the lightcurves

### ISSUE THREAD

**Issue by bszzhzxyf** [asas-sn/skypatrol#6]

**Comment by bszzhzxyf** [comment]
I use skypatrol with python, but the lightcurve table did not tell me the optical band or filter of it? g or V band?

**Comment by gonzodeveloper** [comment]
Apologies for the late response. We've been going through a lot of development and maintenance before the full release this month. 

The most recent version of the client will give you the corresponding filter for each point of photometry. Each lightcurve will be automatically served with V and g band. However you can filter for which ever your interested in through the lightcurve functions or directly in lightcurve.data.
