### ISSUE TITLE
error on downloading curve

### ISSUE THREAD

**Issue by giorgio-grag** [asas-sn/skypatrol#7]
Hi, I have an error when try to downlaod the light curve:

```
  File "D:\WPy64-3850\python-3.8.5.amd64\lib\site-packages\pyasassn\client.py", line 456, in _get_lightcurve_chunk
    count = len(data[id_col].unique())

TypeError: 'NoneType' object is not subscriptable

```
this is my simple code:
```
from pyasassn.client import SkyPatrolClient
client = SkyPatrolClient()
gaiaid = 424422620878989824
query= "SELECT asas_sn_id, ra_deg, dec_deg, gaia_id FROM stellar_main WHERE gaia_id ="+ str(gaiaid)
lcs = client.adql_query(query,download=True, threads=8)
```

**Comment by gonzodeveloper** [comment]
We must have been going through a maintenance period at that time. Over the last 2 months there has been a lot of reworking our pipeline in preparation for our full release. 

This query should work fine now assuming you have the updated python client.

FYI, multi-threading is used for downloading multiple light curves, having 8 threads does nothing here.
