### ISSUE TITLE
ASAS-SN data is differ from web version data.

### ISSUE THREAD

**Issue by DavidIsrayelyan** [asas-sn/skypatrol#9]
Dear Colleagues,

I am trying to download the light curve of blazars using skypatrol python version. In the web interface (https://asas-sn.osu.edu), we simply provide the name of the object or the coordinates and it returns the data in the format
HJD	UT Date	Camera	Filter	FWHM	Limit	Mag	Mag Error	Flux (mJy)	Flux Error

Can you please tell me how I can download the same data by specifying the coordinates using SkyPatrolClient ?

**Comment by gonzodeveloper** [comment]
The interface at the OSU site interacts with a different photometry pipelines that the system backing up our SkyPatrol client provided here. If you want to get the web interface that corresponds to this client's pipeline please visit [(http://asas-sn.ifa.hawaii.edu/skypatrol/)].  Further documentation is also available there as well.

**Comment by DavidIsrayelyan** [comment]
Dear Kyle Hart,

Thank you for your answer. We have tried both web pages and compared the results.
However, we are interested in having the light curves of blazars in the form given below (from https://asas-sn.osu.edu) 

HJD,UT Date,Camera,FWHM,Limit,mag,mag_err,flux(mJy),flux_err,Filter
2457008.77839,2014-12-17.2753820,ba,2.03,16.261,13.501,0.017,15.248,0.245,V
2457008.77981,2014-12-17.2768063,ba,2.05,16.238,13.505,0.018,15.206,0.251,V
2457009.77489,2014-12-18.2719385,ba,1.75,16.339,13.538,0.017,14.751,0.228,V
2457009.77631,2014-12-18.2733550,ba,1.67,16.264,13.529,0.018,14.871,0.243,V
2457010.77479,2014-12-19.2718802,ba,2.03,14.452,13.974,0.143,9.868,1.285,V 

I would like to ask if there is any possibility to download the light curves in the above mentioned format using python?

Or there is any other way to download ASAS-SN light curves for different blazars e.g. using API from https://asas-sn.osu.edu?

Thank you in advance
Best regards
